### ISSUE TITLE
What's the license?

### ISSUE THREAD

**Issue by shinya7y** [SHI-Labs/Convolutional-MLPs#1]
Hi, thank you for publishing the nice CNNs designed with recently popular modules in the MLP literature (LayerNorm, GELU, DropPath).

I would be grateful if you could add a LICENSE file.
I think the Apache License 2.0 is the current best choice because it is useful for many users and adopted by timm, mmdetection, mmsegmentation, and detectron2.

**Comment by honghuis** [comment]
done.

**Comment by shinya7y** [comment]
Thank you very much for your quick response!
